on:
  push:
    branches: [main]
    paths:
      - 'k8s/**'
      - 'Dockerfile'
      - '.github/workflows/deploy-gke.yaml'
name: Deploy to GKE
concurrency:
  group: deploy-gke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Build & Push Docker Image
        run: |
          IMAGE_URI=us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sr-eng-docker/syllo-nginx:${{ github.sha }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials srel-cluster --zone us-east1-b --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply K8s Manifests
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/demo-nginx demo-nginx=$IMAGE_URI
          kubectl rollout status deployment/demo-nginx
